apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid19-spread-analysis
  labels:
    app: covid19-spread-analysis
spec:
  selector:
    matchLabels:
      app: covid19-spread-analysis
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  minReadySeconds: 60
  progressDeadlineSeconds: 1800
  template:
    metadata:
      labels:
        app: covid19-spread-analysis
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: covid19-spread-analysis
        image: mouryaa/covid19-spread-analysis
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            scheme: HTTP
            port: 80
          successThreshold: 1
          periodSeconds: 30
          failureThreshold: 3
          timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: "service-covid19-spread-analysis"
spec:
  selector:
    app: covid19-spread-analysis
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
